data:
  metrix: \CocoData\val_coco_dataset_without_obj
model:
  # The id of the model from models.py from 0 to {MODELS_COUNT - 1}
  id: 2                  # Unique identifier for the model.
  # The name of the model from models.py one of {NAMES}
  name:                  # Optional: Custom model name.
  # The path or directory to model weights which will be loaded
  weights: \train_results\UNet_MobileNetv3\2025-05-16\res_1\weights.pt # Optional: Path to pretrained weights.
metrix_evaluation:
  # The number of workers for data loading during training
  workers: 0
  # The size of the batch for simultaneous usage of samples during training
  batch: 64
threshold_settings:
  # The threshold for labeling the prediction 0 or 1
  thresholds: [ 0, 1, 100 ]
  # If not exists the plots of current training run will be saved in results folder
  no_plot: false
  # The level of detail of printing
  print: 2


